
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 80
#define YY_END_OF_BUFFER 81
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[143] =
    {   0,
        0,    0,    0,    0,   10,   10,   81,   79,   77,   78,
       78,   62,    2,   75,   60,   63,    7,   49,   50,   59,
       57,   48,   58,   55,   56,   72,   46,   47,   67,   61,
       68,   45,   76,   53,   79,   54,   65,   51,   64,   52,
       66,   14,   13,   14,   10,   11,   77,   78,   36,    2,
        1,   22,   74,   73,   29,   22,   32,    7,    6,    7,
       22,   27,   23,   72,   25,   24,   26,   41,    0,   70,
        9,    8,   28,   71,   72,   19,   19,   42,   43,    0,
       38,   35,   44,   37,    0,   76,    0,   33,   34,   40,
       12,   10,   22,   74,   73,    7,    3,    7,    0,    7,

        6,   15,   15,   21,    0,   15,   70,    0,   19,   19,
        0,   19,   30,   31,    0,    5,    5,    4,    4,   21,
        0,   70,    0,   20,   20,    0,   71,   69,   19,   17,
        0,    0,   18,    0,   18,   19,   17,    0,    0,   18,
       18,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,    7,   27,   27,   27,   27,   28,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       29,   30,   31,   32,   27,    1,   33,   33,   27,   27,

       28,   33,   27,   27,   27,   27,   27,   27,   27,   33,
       27,   27,   27,   33,   27,   33,   27,   33,   27,   27,
       27,   27,   34,   35,   36,   37,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[38] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[150] =
    {   0,
        0,    0,   35,   36,  280,  273,  272,  328,  260,  328,
      253,  222,  237,   43,  209,   31,   31,  328,  328,   29,
       40,  328,   49,   26,   54,   62,  207,  328,   61,   20,
       62,  328,   72,  328,  195,  328,  198,  328,   23,  328,
      328,  328,  328,  191,    0,  328,  205,  328,  328,  196,
      328,   89,   84,   87,  328,  115,  328,  187,  328,  145,
      118,  328,  166,   74,  328,  158,  328,  328,  152,   90,
      328,  145,  328,  110,    0,  113,  165,  328,  328,  137,
      328,  328,  328,  328,  121,  116,  112,  328,  328,  328,
      328,    0,  145,  129,  140,  129,  328,  127,  124,  109,

      106,  163,  328,   96,  180,  328,  184,  194,  196,  199,
      146,  211,  328,  328,   78,  328,  328,  328,  328,   84,
      163,  167,  169,  207,  231,  171,  186,  229,  251,  268,
      261,  201,  233,  217,  235,  288,  222,  278,  249,  286,
      254,  328,  321,  323,   87,   82,   79,   65,  325
    } ;

static const flex_int16_t yy_def[150] =
    {   0,
      142,    1,  143,  143,  144,  144,  142,  142,  142,  142,
      142,  142,  145,  142,   14,   14,  146,  142,  142,   14,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  142,  142,  142,  142,   14,  142,  142,  142,
      142,  142,  142,  142,  147,  142,  142,  142,  142,  145,
      142,  142,  142,  142,  142,  142,  142,  148,  142,  149,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  142,  142,   26,  142,  142,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  147,  142,  142,  142,  148,  142,  148,  142,  148,

      142,  142,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  130,  142,  142,  142,
      142,    0,  142,  142,  142,  142,  142,  142,  142
    } ;

static const flex_int16_t yy_nxt[366] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   26,
       27,   28,   29,   30,   31,   32,   33,   33,   34,   35,
       36,   37,   33,   38,   39,   40,   41,   43,   43,   56,
       59,   61,   69,   82,   70,   70,   89,   44,   44,   52,
       52,   52,   62,   63,   57,   52,   83,   90,   64,   64,
       60,   53,   53,   65,   66,   96,   71,   64,   64,   54,
       54,   72,   67,   68,   52,   54,   79,   73,   74,   92,
       75,   75,   58,   80,   81,   84,   85,   50,   76,   77,
       86,   86,   64,   64,   76,   93,   93,   93,   86,   86,

      120,   93,   53,   53,   86,   95,   95,  103,   70,   70,
       94,   94,  120,   95,   95,  119,   94,  105,  118,   95,
       93,   93,   93,   93,   93,   93,   93,   93,  107,  107,
      102,  109,  109,  117,   86,   86,  116,  108,   59,  110,
      110,  115,   86,   86,  114,  110,   93,   99,   86,   93,
      100,   93,   93,   93,  101,   94,   94,   93,   95,   95,
      113,   94,  106,  100,  128,  128,   95,   95,  104,   93,
       93,   93,   95,  103,  100,   93,   93,  100,  111,  103,
      111,  122,  122,  112,  112,  122,  122,  130,  130,  127,
      127,  110,  110,  121,   93,  121,   97,  110,  122,  122,

      123,   51,  107,  107,  127,  127,   47,  126,   91,  126,
      124,  125,  127,  127,  109,  109,  124,  109,  109,  135,
      135,   88,  109,  109,   87,  110,  110,   78,  109,  112,
      112,  110,   55,  124,  124,  137,  137,  109,  129,  124,
      137,  137,   51,  109,  121,   49,  121,  128,  128,  122,
      122,  133,  133,  135,  135,   48,  131,  124,  124,  109,
      136,   47,  138,  124,  132,  109,  132,  141,  141,  133,
      133,  142,  141,  141,  132,   46,  132,  109,  109,  135,
      135,  138,   46,  109,  134,  142,  130,  130,  142,  142,
      142,  139,  142,  139,  124,  124,  141,  141,  142,  142,

      124,  139,  142,  139,  140,  140,  140,  140,  142,  142,
      142,  142,  109,  136,  109,  109,  142,  142,  109,  142,
      109,   42,   42,   45,   45,   98,   98,    7,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  142,  142,  142
    } ;

static const flex_int16_t yy_chk[366] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    4,   16,
       17,   20,   24,   30,   24,   24,   39,    3,    4,   14,
       14,   14,   20,   21,   16,   14,   30,   39,   21,   21,
       17,   14,   14,   21,   23,  148,   25,   23,   23,   14,
       14,   25,   23,   23,   14,   14,   29,   25,   26,  147,
       26,   26,  146,   29,   29,   31,   31,  145,   26,   26,
       33,   33,   64,   64,   26,   52,   52,   52,   33,   33,

      120,   52,   53,   53,   33,   54,   54,  115,   70,   70,
       53,   53,  104,   54,   54,  101,   53,   70,  100,   54,
       52,   56,   56,   56,   61,   61,   61,   56,   74,   74,
       61,   76,   76,   99,   86,   86,   98,   74,   96,   76,
       76,   87,   86,   86,   85,   76,   56,   60,   86,   61,
       60,   93,   93,   93,   60,   94,   94,   93,   95,   95,
       80,   94,   72,   60,  111,  111,   95,   95,   69,  102,
      102,  102,   95,   66,   60,  102,   93,   60,   77,   63,
       77,  121,  121,   77,   77,  122,  122,  123,  123,  126,
      126,   77,   77,  105,  102,  105,   58,   77,  105,  105,

      107,   50,  107,  107,  127,  127,   47,  108,   44,  108,
      107,  107,  108,  108,  109,  109,  107,  110,  110,  132,
      132,   37,  109,  109,   35,  110,  110,   27,  109,  112,
      112,  110,   15,  124,  124,  134,  134,  112,  112,  124,
      137,  137,   13,  112,  125,   12,  125,  128,  128,  125,
      125,  133,  133,  135,  135,   11,  128,  125,  125,  133,
      133,    9,  135,  125,  129,  133,  129,  139,  139,  129,
      129,    7,  141,  141,  131,    6,  131,  129,  129,  131,
      131,  141,    5,  129,  130,    0,  130,  130,    0,    0,
        0,  138,    0,  138,  130,  130,  138,  138,    0,    0,

      130,  136,    0,  136,  140,  140,  136,  136,    0,    0,
        0,    0,  140,  140,  136,  136,    0,    0,  140,    0,
      136,  143,  143,  144,  144,  149,  149,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  142,  142,  142
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "urdu_lexer.l"
#line 2 "urdu_lexer.l"
#include <stdio.h>
#include <string.h>
#include <ctype.h>

FILE *token_file;
FILE *error_file;
int line_no = 1;
int total_tokens = 0;
int total_errors = 0;

int in_comment = 0;

int is_keyword(const char *s) {
    const char *keywords[] = {
        "hum", "tum", "Wapas", "Agar", "Adadi", "Mantiqi", "shuru", "khatam",
        "jabtak", "warna", "magar", "ucp", "socho", "dalo", "rahko", "pakka",
        "aur", "keliye", "lo", "sahi", "galat", "ya", "nahi", "kaam", "wapis", "hatao",
        "output<-", NULL
    };
    for (int i = 0; keywords[i] != NULL; i++)
        if (strcmp(s, keywords[i]) == 0)
            return 1;
    return 0;
}

const char* get_operator_name(const char *s) {
    if (strcmp(s, "+") == 0) return "PLUS";
    if (strcmp(s, "-") == 0) return "MINUS";
    if (strcmp(s, "*") == 0) return "MULTIPLY";
    if (strcmp(s, "/") == 0) return "DIVIDE";
    if (strcmp(s, "%") == 0) return "MODULO";
    if (strcmp(s, "++") == 0) return "INCREMENT";
    if (strcmp(s, "--") == 0) return "DECREMENT";
    
    if (strcmp(s, "=") == 0) return "ASSIGN";
    if (strcmp(s, "+=") == 0) return "PLUS_ASSIGN";
    if (strcmp(s, "-=") == 0) return "MINUS_ASSIGN";
    if (strcmp(s, "*=") == 0) return "MULTIPLY_ASSIGN";
    if (strcmp(s, "/=") == 0) return "DIVIDE_ASSIGN";
    if (strcmp(s, "%=") == 0) return "MODULO_ASSIGN";
    if (strcmp(s, "<<=") == 0) return "LEFT_SHIFT_ASSIGN";
    if (strcmp(s, ">>=") == 0) return "RIGHT_SHIFT_ASSIGN";
    if (strcmp(s, "&=") == 0) return "BITWISE_AND_ASSIGN";
    if (strcmp(s, "^=") == 0) return "BITWISE_XOR_ASSIGN";
    if (strcmp(s, "|=") == 0) return "BITWISE_OR_ASSIGN";
    
    if (strcmp(s, "==") == 0) return "EQUAL";
    if (strcmp(s, "!=") == 0) return "NOT_EQUAL";
    if (strcmp(s, ">") == 0) return "GREATER";
    if (strcmp(s, "<") == 0) return "LESS";
    if (strcmp(s, ">=") == 0) return "GREATER_EQUAL";
    if (strcmp(s, "<=") == 0) return "LESS_EQUAL";

    if (strcmp(s, "&&") == 0) return "AND";
    if (strcmp(s, "||") == 0) return "OR";
    if (strcmp(s, "!") == 0) return "NOT";
 
    if (strcmp(s, "&") == 0) return "BITWISE_AND";
    if (strcmp(s, "|") == 0) return "BITWISE_OR";
    if (strcmp(s, "^") == 0) return "BITWISE_XOR";
    if (strcmp(s, "~") == 0) return "BITWISE_NOT";
    if (strcmp(s, "<<") == 0) return "LEFT_SHIFT";
    if (strcmp(s, ">>") == 0) return "RIGHT_SHIFT";

    if (strcmp(s, "->") == 0) return "ARROW";
    if (strcmp(s, ".") == 0) return "DOT";
    if (strcmp(s, "?:") == 0) return "TERNARY";
    if (strcmp(s, "::") == 0) return "SCOPE";
    if (strcmp(s, "<-") == 0) return "ASSIGN_LEFT";
    if (strcmp(s, "=~") == 0) return "PATTERN_MATCH";
    
    return "OPERATOR";
}

const char* get_punctuation_name(const char *s) {
    if (strcmp(s, ";") == 0) return "SEMICOLON";
    if (strcmp(s, ",") == 0) return "COMMA";
    if (strcmp(s, "(") == 0) return "LEFT_PAREN";
    if (strcmp(s, ")") == 0) return "RIGHT_PAREN";
    if (strcmp(s, "{") == 0) return "LEFT_BRACE";
    if (strcmp(s, "}") == 0) return "RIGHT_BRACE";
    if (strcmp(s, "[") == 0) return "LEFT_BRACKET";
    if (strcmp(s, "]") == 0) return "RIGHT_BRACKET";
    if (strcmp(s, ":") == 0) return "COLON";
    if (strcmp(s, "?") == 0) return "QUESTION";
    if (strcmp(s, ".") == 0) return "DOT";
    
    return "PUNCTUATION";
}

int is_integer(const char *s) {
    int i = 0;
    if (s[i] == '+' || s[i] == '-') i++;
    if (!isdigit(s[i])) return 0;
    for (; s[i]; i++)
        if (!isdigit(s[i])) return 0;
    return 1;
}

int is_float(const char *s) {
    int i = 0, dot = 0;
    if (s[i] == '+' || s[i] == '-') i++;
    int digits_before = 0, digits_after = 0;
    
    while (isdigit(s[i])) {
        digits_before++;
        i++;
    }
    
    if (s[i] == '.') {
        dot = 1;
        i++;
    }
  
    while (isdigit(s[i])) {
        digits_after++;
        i++;
    }
    
    return (digits_before > 0 || digits_after > 0) && dot == 1 && s[i] == '\0';
}

int is_exponential(const char *s) {
    int i = 0, dot = 0, e_seen = 0, digits_before_e = 0, digits_after_e = 0;
    
    if (s[i] == '+' || s[i] == '-') i++;
    
    while (isdigit(s[i])) {
        digits_before_e++;
        i++;
    }

    if (s[i] == '.') {
        dot = 1;
        i++;
        while (isdigit(s[i])) {
            digits_before_e++;
            i++;
        }
    }
    
    if (s[i] == 'e' || s[i] == 'E') {
        e_seen = 1;
        i++;
        
        if (s[i] == '+' || s[i] == '-') i++;

        while (isdigit(s[i])) {
            digits_after_e++;
            i++;
        }
    }
    
    return digits_before_e > 0 && (e_seen == 0 || digits_after_e > 0) && s[i] == '\0';
}

int is_valid_identifier(const char *s) {
    if (!isalpha(s[0]) && s[0] != '_')
        return 0;
    for (int i = 1; s[i]; i++)
        if (!isalnum(s[i]) && s[i] != '_')
            return 0;
    return 1;
}

int is_special_identifier(const char *s) {
    if (s[0] == '@' || s[0] == '#' || s[0] == '$' || s[0] == '%' || 
        s[0] == '^' || s[0] == '&' || s[0] == '*') {
        return 1;
    }
    return 0;
}

const char* get_special_identifier_type(const char *s) {
    if (isdigit(s[1])) {
        return "INVALID_NUMBER";
    } else if (isalpha(s[1]) || s[1] == '_') {
        return "INVALID_IDENTIFIER";
    } else {
        return "UNKNOWN_TOKEN";
    }
}

int is_operator(const char *s) {
    const char *ops[] = {
        "+", "-", "*", "/", "%", "++", "--",
        "=", "+=", "-=", "*=", "/=", "%=", "<<=", ">>=", "&=", "^=", "|=",
        "==", "!=", ">", "<", ">=", "<=",
        "&&", "||", "!",
        "&", "|", "^", "~", "<<", ">>",
        "->", ".", "?:", "::", "<-", "=~",
        NULL
    };
    for (int i = 0; ops[i] != NULL; i++)
        if (strcmp(s, ops[i]) == 0)
            return 1;
    return 0;
}

int is_punctuation(const char *s) {
    const char *puncs[] = {
        ";", ",", "(", ")", "{", "}", "[", "]", ":", "?", ".",
        NULL
    };
    for (int i = 0; puncs[i] != NULL; i++)
        if (strcmp(s, puncs[i]) == 0)
            return 1;
    return 0;
}

int is_string_literal(const char *s) {
    int len = strlen(s);
    if (len < 2 || s[0] != '"' || s[len-1] != '"') return 0;
    
    for (int i = 1; i < len-1; i++) {
        if (s[i] == '\\') {
            i++;
            if (i >= len-1) return 0;
            char next = s[i];
            if (next != 'n' && next != 't' && next != 'r' && next != '\\' && 
                next != '"' && next != '0' && next != 'a' && next != 'b' && next != 'f' &&
                next != 'v' && next != '\'') {
                return 0;
            }
        }
    }
    return 1;
}

int is_char_literal(const char *s) {
    int len = strlen(s);
    if (len < 3 || s[0] != '\'' || s[len-1] != '\'') return 0;
    
    if (len == 2) return 0;
    
    if (len == 3) return 1;

    if (len == 4 && s[1] == '\\') {
        char esc = s[2];
        if (esc != 'n' && esc != 't' && esc != 'r' && esc != '\\' && 
            esc != '\'' && esc != '0' && esc != 'a' && esc != 'b' && esc != 'f' &&
            esc != 'v') {
            return 1;
        }
        return 0;
    }
    
    return 0;
}

int has_multiple_dots(const char *s) {
    int dot_count = 0;
    for (int i = 0; s[i]; i++) {
        if (s[i] == '.') dot_count++;
    }
    return dot_count > 1;
}

int has_multiple_exponents(const char *s) {
    int e_count = 0;
    for (int i = 0; s[i]; i++) {
        if (s[i] == 'e' || s[i] == 'E') e_count++;
    }
    return e_count > 1;
}

int has_consecutive_operators(const char *s) {
    return strstr(s, "+++") || strstr(s, "---") || strstr(s, "***") || 
           strstr(s, "///") || strstr(s, "\\\\\\\\");
}

int is_mixed_alphanumeric(const char *s) {
    int has_alpha = 0, has_digit = 0;
    for (int i = 0; s[i]; i++) {
        if (isalpha(s[i])) has_alpha = 1;
        if (isdigit(s[i])) has_digit = 1;
        if (has_alpha && has_digit) return 1;
    }
    return 0;
}

const char* detect_token_type(const char *tok) {
    if (has_multiple_dots(tok) && (isdigit(tok[0]) || tok[0] == '.')) 
        return "INVALID_NUMBER_MULTIPLE_DOTS";
    
    if (has_multiple_exponents(tok)) 
        return "INVALID_NUMBER_MULTIPLE_EXPONENTS";
    
    if (has_consecutive_operators(tok)) 
        return "INVALID_OPERATOR_COMBINATION";
    
    if (is_string_literal(tok)) return "STRING";
    if (is_char_literal(tok)) return "CHAR";
    if (is_exponential(tok)) return "NUMBER_EXP";
    if (is_float(tok)) return "NUMBER_FLOAT";
    if (is_integer(tok)) return "NUMBER_INT";
    if (is_keyword(tok)) return "KEYWORD";
    if (is_operator(tok)) return get_operator_name(tok);
    if (is_punctuation(tok)) return get_punctuation_name(tok);
    if (is_valid_identifier(tok)) return "IDENTIFIER";
    
    if (is_special_identifier(tok)) {
        return get_special_identifier_type(tok);
    }
    
    if (isdigit(tok[0]) || tok[0] == '+' || tok[0] == '-' || tok[0] == '.') {
        return "INVALID_NUMBER";
    }
    
    if (tok[0] == '"') return "INVALID_STRING";
    if (tok[0] == '\'') return "INVALID_CHAR";
    
    if (strstr(tok, "+++") || strstr(tok, "---") || strstr(tok, "***") || 
        strstr(tok, "///") || strstr(tok, "\\\\\\\\")) {
        return "INVALID_OPERATOR";
    }
    
    if (isdigit(tok[0]) && is_mixed_alphanumeric(tok)) {
        return "INVALID_NUMBER_FORMAT";
    }
    
    return "UNKNOWN_TOKEN";
}

const char* detect_error_reason(const char *tok) {
    int len = strlen(tok);
    
    if (has_multiple_dots(tok)) 
        return "invalid number - multiple decimal points";
    
    if (has_multiple_exponents(tok)) 
        return "invalid number - multiple exponents";
    
    if (has_consecutive_operators(tok)) 
        return "invalid operator - consecutive operators not allowed";
    
    if (is_special_identifier(tok)) {
        if (isdigit(tok[1])) {
            return "invalid number - cannot start with special character";
        } else if (isalpha(tok[1]) || tok[1] == '_') {
            return "identifier cannot start with special character";
        } else {
            return "invalid token starting with special character";
        }
    }
    
    if (isdigit(tok[0]) && !is_integer(tok) && !is_float(tok) && !is_exponential(tok)) {
        for (int i = 0; tok[i]; i++) {
            if (isalpha(tok[i]) || tok[i] == '_') {
                return "identifier cannot start with digit";
            }
        }
    }
    
    if (isdigit(tok[0]) || tok[0] == '+' || tok[0] == '-' || tok[0] == '.') {
        int dot_count = 0, e_count = 0, digit_count = 0;
        
        for (int i = 0; tok[i]; i++) {
            if (isdigit(tok[i])) digit_count++;
            else if (tok[i] == '.') dot_count++;
            else if (tok[i] == 'e' || tok[i] == 'E') e_count++;
            else if (tok[i] == '+' || tok[i] == '-') {
                if (i > 0 && (tok[i-1] != 'e' && tok[i-1] != 'E')) {
                    return "invalid number format - sign not allowed here";
                }
            }
            else if (isalpha(tok[i])) {
                return "invalid number - contains letters";
            }
            else {
                return "invalid number - contains illegal characters";
            }
        }
        
        if (dot_count > 1) return "invalid number - multiple decimal points";
        if (e_count > 1) return "invalid number - multiple exponents";
        if (digit_count == 0) return "invalid number - no digits found";
        
        return "invalid number format";
    }
    
    if (tok[0] == '"') {
        if (tok[len-1] != '"') return "unterminated string literal";
        
        for (int i = 1; i < len-1; i++) {
            if (tok[i] == '\\') {
                i++;
                if (i >= len-1) return "incomplete escape sequence";
                char esc = tok[i];
                if (esc != 'n' && esc != 't' && esc != 'r' && esc != '\\' && 
                    esc != '"' && esc != '0' && esc != 'a' && esc != 'b' && esc != 'f' &&
                    esc != 'v' && esc != '\'') {
                    return "invalid escape sequence";
                }
            }
        }
        return "invalid string format";
    }
    
    if (tok[0] == '\'') {
        if (tok[len-1] != '\'') return "unterminated character literal";
        if (len == 2) return "empty character literal";
        if (len > 4) return "character literal too long";
        
        if (len == 4 && tok[1] == '\\') {
            char esc = tok[2];
            if (esc != 'n' && esc != 't' && esc != 'r' && esc != '\\' && 
                esc != '\'' && esc != '0' && esc != 'a' && esc != 'b' && esc != 'f' &&
                esc != 'v') {
                return "invalid escape sequence in character";
            }
        }
        
        if (len > 3 && tok[1] != '\\') return "character literal too long";
        return "invalid character format";
    }
    
    if (strstr(tok, "+++") || strstr(tok, "---") || strstr(tok, "***") || 
        strstr(tok, "///") || strstr(tok, "\\\\\\\\")) {
        return "invalid operator combination";
    }
    
    if (!is_valid_identifier(tok) && (isalpha(tok[0]) || tok[0] == '_')) {
        for (int i = 0; tok[i]; i++) {
            if (!isalnum(tok[i]) && tok[i] != '_') {
                return "identifier contains invalid characters";
            }
        }
    }
    
    if (len == 1 && !isalnum(tok[0]) && tok[0] != '_') {
        if (!is_operator(tok) && !is_punctuation(tok)) {
            return "unknown symbol";
        }
    }

    if (len > 1 && !is_operator(tok) && !is_keyword(tok) && !is_valid_identifier(tok)) {
        return "unrecognized token";
    }
    
    return "invalid token format";
}

void print_token(const char *type, const char *val) {
    printf("Line %d: %s -> %s\n", line_no, type, val);
    fprintf(token_file, "Line %d: %s -> %s\n", line_no, type, val);
    total_tokens++;
}

void print_error_with_type(const char *type, const char *val, const char *msg) {
    printf("Line %d: %s -> %s (ERROR: %s)\n", line_no, type, val, msg);
    fprintf(error_file, "Line %d: %s -> %s (ERROR: %s)\n", line_no, type, val, msg);
    total_errors++;
    total_tokens++;
}

void handle_token(const char *tok) {
    if (tok[0] == '\0') return;
    
    const char *token_type = detect_token_type(tok);
    
    if (strcmp(token_type, "UNKNOWN_TOKEN") != 0 && 
        strstr(token_type, "INVALID_") == NULL) {
        print_token(token_type, tok);
    } else {
        const char *reason = detect_error_reason(tok);
        print_error_with_type(token_type, tok, reason);
    }
}
#line 1040 "lex.yy.c"

#line 1042 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1
#define SINGLE_COMMENT 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 477 "urdu_lexer.l"


#line 1264 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 143 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 328 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 479 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 480 "urdu_lexer.l"
{ 
    fprintf(error_file, "Line %d: INVALID_STRING -> %s (ERROR: unterminated string literal)\n", line_no, yytext);
    printf("Line %d: INVALID_STRING -> %s (ERROR: unterminated string literal)\n", line_no, yytext);
    total_errors++;
    total_tokens++;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 487 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 488 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 489 "urdu_lexer.l"
{ 
    fprintf(error_file, "Line %d: INVALID_CHAR -> %s (ERROR: invalid escape sequence in character)\n", line_no, yytext);
    printf("Line %d: INVALID_CHAR -> %s (ERROR: invalid escape sequence in character)\n", line_no, yytext);
    total_errors++;
    total_tokens++;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 495 "urdu_lexer.l"
{ 
    fprintf(error_file, "Line %d: INVALID_CHAR -> %s (ERROR: character literal too long)\n", line_no, yytext);
    printf("Line %d: INVALID_CHAR -> %s (ERROR: character literal too long)\n", line_no, yytext);
    total_errors++;
    total_tokens++;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 501 "urdu_lexer.l"
{ 
    fprintf(error_file, "Line %d: INVALID_CHAR -> %s (ERROR: unterminated character literal)\n", line_no, yytext);
    printf("Line %d: INVALID_CHAR -> %s (ERROR: unterminated character literal)\n", line_no, yytext);
    total_errors++;
    total_tokens++;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 508 "urdu_lexer.l"
{ BEGIN(SINGLE_COMMENT); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 509 "urdu_lexer.l"
{ BEGIN(COMMENT); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 511 "urdu_lexer.l"
{ /* ignore single-line comment */ }
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 512 "urdu_lexer.l"
{ BEGIN(INITIAL); line_no++; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 514 "urdu_lexer.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 515 "urdu_lexer.l"
{ line_no++; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 516 "urdu_lexer.l"
{ /* ignore comment content */ }
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 517 "urdu_lexer.l"
{ 
    fprintf(error_file, "Line %d: ERROR -> Unterminated multi-line comment\n", line_no);
    printf("Line %d: ERROR -> Unterminated multi-line comment\n", line_no);
    BEGIN(INITIAL); 
    total_errors++;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 524 "urdu_lexer.l"
{ 
    fprintf(error_file, "Line %d: INVALID_OPERATOR_COMBINATION -> %s (ERROR: invalid operator - consecutive operators not allowed)\n", line_no, yytext);
    printf("Line %d: INVALID_OPERATOR_COMBINATION -> %s (ERROR: invalid operator - consecutive operators not allowed)\n", line_no, yytext);
    total_errors++;
    total_tokens++;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 531 "urdu_lexer.l"
{ 
    fprintf(error_file, "Line %d: INVALID_OPERATOR -> %s (ERROR: invalid operator combination)\n", line_no, yytext);
    printf("Line %d: INVALID_OPERATOR -> %s (ERROR: invalid operator combination)\n", line_no, yytext);
    total_errors++;
    total_tokens++;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 538 "urdu_lexer.l"
{ 
    fprintf(error_file, "Line %d: INVALID_NUMBER_MULTIPLE_DOTS -> %s (ERROR: invalid number - multiple decimal points)\n", line_no, yytext);
    printf("Line %d: INVALID_NUMBER_MULTIPLE_DOTS -> %s (ERROR: invalid number - multiple decimal points)\n", line_no, yytext);
    total_errors++;
    total_tokens++;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 545 "urdu_lexer.l"
{ 
    fprintf(error_file, "Line %d: INVALID_NUMBER_MULTIPLE_EXPONENTS -> %s (ERROR: invalid number - multiple exponents)\n", line_no, yytext);
    printf("Line %d: INVALID_NUMBER_MULTIPLE_EXPONENTS -> %s (ERROR: invalid number - multiple exponents)\n", line_no, yytext);
    total_errors++;
    total_tokens++;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 552 "urdu_lexer.l"
{ 
    fprintf(error_file, "Line %d: INVALID_NUMBER_FORMAT -> %s (ERROR: identifier cannot start with digit)\n", line_no, yytext);
    printf("Line %d: INVALID_NUMBER_FORMAT -> %s (ERROR: identifier cannot start with digit)\n", line_no, yytext);
    total_errors++;
    total_tokens++;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 559 "urdu_lexer.l"
{ 
    fprintf(error_file, "Line %d: INVALID_NUMBER_FORMAT -> %s (ERROR: invalid number format - mixed digits and letters)\n", line_no, yytext);
    printf("Line %d: INVALID_NUMBER_FORMAT -> %s (ERROR: invalid number format - mixed digits and letters)\n", line_no, yytext);
    total_errors++;
    total_tokens++;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 566 "urdu_lexer.l"
{ 
    fprintf(error_file, "Line %d: INVALID_OPERATOR_COMBINATION -> %s (ERROR: invalid operator - multiple dots)\n", line_no, yytext);
    printf("Line %d: INVALID_OPERATOR_COMBINATION -> %s (ERROR: invalid operator - multiple dots)\n", line_no, yytext);
    total_errors++;
    total_tokens++;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 573 "urdu_lexer.l"
{ 
    fprintf(error_file, "Line %d: INVALID_SYMBOL_COMBINATION -> %s (ERROR: invalid symbol combination)\n", line_no, yytext);
    printf("Line %d: INVALID_SYMBOL_COMBINATION -> %s (ERROR: invalid symbol combination)\n", line_no, yytext);
    total_errors++;
    total_tokens++;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 580 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 581 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 582 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 583 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 584 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 585 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 586 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 587 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 588 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 589 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 590 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 591 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 592 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 593 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 594 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 595 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 596 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 597 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 598 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 599 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 600 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 601 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 602 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 603 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 605 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 606 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 607 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 608 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 609 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 610 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 611 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 612 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 613 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 615 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 616 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 617 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 618 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 619 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 620 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 621 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 622 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 623 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 624 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 625 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 626 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 627 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 629 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 630 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 631 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 632 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 634 "urdu_lexer.l"
{ 
    fprintf(error_file, "Line %d: INVALID_IDENTIFIER -> %s (ERROR: identifier cannot start with special character)\n", line_no, yytext);
    printf("Line %d: INVALID_IDENTIFIER -> %s (ERROR: identifier cannot start with special character)\n", line_no, yytext);
    total_errors++;
    total_tokens++;
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 641 "urdu_lexer.l"
{ 
    fprintf(error_file, "Line %d: INVALID_NUMBER -> %s (ERROR: invalid number - cannot start with special character)\n", line_no, yytext);
    printf("Line %d: INVALID_NUMBER -> %s (ERROR: invalid number - cannot start with special character)\n", line_no, yytext);
    total_errors++;
    total_tokens++;
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 648 "urdu_lexer.l"
{ 
    fprintf(error_file, "Line %d: INVALID_SYMBOL -> %s (ERROR: invalid standalone symbol)\n", line_no, yytext);
    printf("Line %d: INVALID_SYMBOL -> %s (ERROR: invalid standalone symbol)\n", line_no, yytext);
    total_errors++;
    total_tokens++;
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 655 "urdu_lexer.l"
{ handle_token(yytext); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 657 "urdu_lexer.l"
{ /* ignore whitespace */ }
	YY_BREAK
case 78:
/* rule 78 can match eol */
YY_RULE_SETUP
#line 658 "urdu_lexer.l"
{ line_no++; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 660 "urdu_lexer.l"
{ 
    fprintf(error_file, "Line %d: UNKNOWN_TOKEN -> %s (ERROR: unknown symbol)\n", line_no, yytext);
    printf("Line %d: UNKNOWN_TOKEN -> %s (ERROR: unknown symbol)\n", line_no, yytext);
    total_errors++;
    total_tokens++;
}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 667 "urdu_lexer.l"
ECHO;
	YY_BREAK
#line 1814 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(SINGLE_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 143 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 143 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 142);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 667 "urdu_lexer.l"


int main(int argc, char *argv[]) {
    token_file = fopen("token.txt", "w");
    error_file = fopen("error.txt", "w");
    
    if (token_file == NULL || error_file == NULL) {
        printf("Error: Could not create output files!\n");
        return 1;
    }
    
    printf("=== Urdu Script Lexical Analyzer ===\n");
    printf("Output files: token.txt, error.txt\n");
    
    if (argc > 1) {
        printf("Reading from file: %s\n\n", argv[1]);
        yyin = fopen(argv[1], "r");
        if (yyin == NULL) {
            printf("Error: Could not open input file %s\n", argv[1]);
            fclose(token_file);
            fclose(error_file);
            return 1;
        }
    } else {
        printf("Enter your code (Press Ctrl+D to end):\n\n");
    }
    
    yylex();
    
    fclose(token_file);
    fclose(error_file);
    
    printf("\n=== Lexical Analysis Completed ===\n");
    printf("Total tokens: %d\n", total_tokens);
    printf("Total errors: %d\n", total_errors);
    printf("Check token.txt for all tokens\n");
    printf("Check error.txt for all errors\n");
    
    if (total_errors == 0) {
        printf("\n🎉 SUCCESS: No lexical errors found!\n");
    } else {
        printf("\n⚠️  Found %d error(s) that need to be fixed.\n", total_errors);
    }
    
    return 0;
}

